steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/spheric-basis-438520-q2/firstname-studentid/image:${COMMIT_SHA}', '.']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/spheric-basis-438520-q2/firstname-studentid/image:${COMMIT_SHA}']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
