steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/spheric-basis-438520-q2/maheep-100909435/image:${COMMIT_SHA}', '.']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/spheric-basis-438520-q2/maheep-100909435/image:${COMMIT_SHA}']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'maheep-100909435', '--image', 'us-central1-docker.pkg.dev/spheric-basis-438520-q2/maheep-100909435/image:${COMMIT_SHA}', '--region', 'us-central1', '--platform', 'managed']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
